// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhoblmFmh7CPMmhS8nG4K0swRgT2G_pk',
    appId: '1:1005403212069:web:c5f06f1b8ff1ea35d5f2cc',
    messagingSenderId: '1005403212069',
    projectId: 'perfumariapontes-77985',
    authDomain: 'perfumariapontes-77985.firebaseapp.com',
    databaseURL: 'https://perfumariapontes-77985-default-rtdb.firebaseio.com',
    storageBucket: 'perfumariapontes-77985.appspot.com',
    measurementId: 'G-0BTZ3NGKF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0RnZhE3yrl_J2MspWGggAQj2VqOgTMhM',
    appId: '1:1005403212069:android:5a8ebc51c3b6aeb8d5f2cc',
    messagingSenderId: '1005403212069',
    projectId: 'perfumariapontes-77985',
    databaseURL: 'https://perfumariapontes-77985-default-rtdb.firebaseio.com',
    storageBucket: 'perfumariapontes-77985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyHhGpnpApnilRmvj1LpwNVssmzJ9LnPE',
    appId: '1:1005403212069:ios:f32b4850b63b7d89d5f2cc',
    messagingSenderId: '1005403212069',
    projectId: 'perfumariapontes-77985',
    databaseURL: 'https://perfumariapontes-77985-default-rtdb.firebaseio.com',
    storageBucket: 'perfumariapontes-77985.appspot.com',
    iosClientId:
        '1005403212069-2727tt3tcuo9sfjc5429678tgij7sq32.apps.googleusercontent.com',
    iosBundleId: 'br.com.wellysonpontes.shop2',
  );
}
